jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttihp25b
        with:
          pdk: ihp

      - name: Upload GDS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ihp-gds
          path: runs/ihp/results/final/gds/
          if-no-files-found: error

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download GDS artifact
        uses: actions/download-artifact@v4
        with:
          name: ihp-gds
          path: runs/ihp/results/final/gds/

      - name: Deploy Viewer
        uses: TinyTapeout/tt-gds-action/viewer@ttihp25b
        with:
          pdk: ihp
