name: test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run equivalence test
        uses: TinyTapeout/tt-gds-action/eqy_test@ttihp25b
        with:
          pdk: ihp
